### ISSUE TITLE
as.matrix(model, which = "docs") returns also (some) words

### ISSUE THREAD

**Issue by michalovadek** [bnosac/doc2vec#15]
while working with the package I encountered what I assume is an error. Trying to extract document embeddings using as.matrix(model, which = "docs"), the resulting matrix contains both documents and words (not all words). I assume it should only contain document vectors. You mention in the README that documents should not be longer than 1000 words. Mine are longer, however. Could this cause the problem? The model seems to work fine otherwise.

**Comment by jwijffels** [comment]
Yes, that is the problem. Documents should not be longer than 1000 words. This is causing that issue where you will find words in your document embeddings.

**Comment by jwijffels** [comment]
The hard limit of 1000 words is defined at https://github.com/bnosac/doc2vec/blob/master/src/doc2vec/common_define.h#L14
Just make sure your documents have less than 1000 words.

**Comment by michalovadek** [comment]
Could you explain a bit the reason for this limit? Other than accessing the document embeddings with the as.matrix() method, the model seems to have worked fine even with longer documents. Allowing for nwords > 1000 might be useful in some cases

**Comment by jwijffels** [comment]
Technically the setting is just at that location and if it needs to be changed, some C++ dynamic memory assignments need to be implemented instead of the fixed array right now
But modelwise I think it makes sense as in the end the doc2vec model is just a combination of word embeddings and a paragraph vector and the longer the text the more there are different meanings in the document.

**Comment by martinbaumgaertner** [comment]
I have a follow-up question here that I can't explain with my rudimentary C++ knowledge: 
Does the limit affect the embedding algorithm, or does it just cause some words to be sorted incorrectly? 

In the latter case, a simple workaround seems to be to simply re-sort the matrices?

Alternatively, I changed MAX_SENTENCE_LENGTH to 10,000 once as a test. This gives me clean document embeddings.I am now a bit unsure if this approach is plausible since it doesn't seem to have any memory issues?

**Comment by jwijffels** [comment]
It does not affect the implemented algorithm, if you decide to increase it, feel free to do so. It just uses more memory. 
The default limit of 1000 means that if you have a document with more than 1000 words, word 1001 will be considered a new document and word 1002 up to the end of the sentence part of that new doc. Nothing related to sorting
